markdown: kramdown
safe: false
permalink: /posts/:title.html
# exclude:
#   - README.md

name: DoerLBH
host: github.io
desc: Updates of my Life with Wonders~

custom:
    category:
        Project: Project
        Idea: Idea
        Paper: Paper
        News: News
        Day: Day
#        Baker: Baker Lab
 #       Olavarria: Olavarria Lab
  #      Teng: Teng Lab
   #     Indie: Indie
    categories:
        - name: Project
          title: Project
        - name: Idea
          title: Idea
        - name: Paper
          title: Paper
        - name: News
          title: News
        - name: Day
          title: Day
#        - name: Baker
 #           title: Baker Lab
  #      - name: Olavarria
   #         title: Olavarria Lab
    #    - name: Teng
     #       title: Teng Lab
      #  - name: Indie
       #     title: Indie

    scrollingLoadCount: 4                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: Baihan Lin
        email: DoerLBH@Gmail.com
        disqus: doerlbh           # Disqus缩略标识
        gcse: 006274521208867279600:ldw93qigkgm    # Google自定义搜索标识ID
        github: doerlbh                 # GitHub账号
        gravatar: c3f17efc644dc613f335001adcd23250  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址

gems:
  - jekyll-feed
